env:
  TERM: xterm-256color
font:
  size: 18
  offset:
    x: 1
    y: 5
key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Key6, mods: Control, chars: "\x1e" }
window:
  decorations: none
  opacity: 0.93
  padding:
    x: 10
    y: 10
  # startup_mode: Maximized
