[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
