env:
  TERM: xterm-256color
font:
  size: 18
  normal:
    family: FiraCode Nerd Font Mono
    style: Light
  bold:
    family: FiraCode Nerd Font Mono
    style: Medium
  # italic:
  #   family: FiraCode Nerd Font Mono
  #   style: Italic
key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Key6, mods: Control, chars: "\x1e" }
window:
  # decorations: none
  opacity: 0.93
  padding:
    x: 10
  #   y: 10
  # startup_mode: Maximized
